### PR TITLE
Missing German umlaut

### PR DESCRIPTION
**Pull request by arifaydogmus**
ß => ss

### CODE REVIEW

**Comment by maxcnunes** [comment]
I think it shouldn't be added to this library. This library seems to cover only accent related diacritics. For full mapping of every diacritics possible, there are other libs for that. Is that right @tyxla ?

**Comment by tyxla** [comment]
Yeah, I can understand why such a character wouldn't be covered, but at the same time, if we follow what WordPress does in its `remove_accents`, it seems to convert that case. So I'm planning to merge that, too - seems like this PR could use a test though.

**Comment by gollenia** [comment]
Ah, just seen there's been a request already. Since the "ß" is very commonly used in germany and Austria, it shold be added. It's a ligature of s and z and has - historically - a similar origin than accents.

**Comment by tyxla** [comment]
On top of the PR missing tests, I'm confused as to whether this should be converted to `sz` or `ss` - I see different opinions on the matter. Thoughts anyone?

**Comment by gollenia** [comment]
the letter exists ONLY in the german language, and it is allways converted to `ss`, never zo `sz`. Why does it matter? Because without it, the package is useless for the german language.

**Comment by tyxla** [comment]
This is addressed by #31

**Comment by tyxla** [comment]
I'm happy to merge the first PR that includes a unit test :wink:

**Comment by tyxla** [comment]
This was addressed by #31 and #32.

**Pull request closed without merging**
