### PR TITLE
Add missing characters (ș, ț)

### PR DESCRIPTION
**Pull request by andreialecu**

### CODE REVIEW

**Comment by andreialecu** [comment]
Ah hold on, I'll clone it locally and fix it.

**Comment by tyxla** [comment]
Awesome, thanks for the contribution, @andreialecu! Do you also wish to add the corresponding capital letters?

**Comment by andreialecu** [comment]
Indeed, forgot about those, one minute please. :)

**Comment by tyxla** [comment]
Thank you @andreialecu! Cheers 😃

**Pull request merged**
