### PR TITLE
Added german "sharp s" ß

### PR DESCRIPTION
**Pull request by gollenia**

### CODE REVIEW

**Comment by tyxla** [comment]
Hey @gollenia, thanks for the contribution!

Would you mind adding a unit test or updating the existing one to cover `ß`?

**Comment by gollenia** [comment]
Hi, I added the unit test - is that ok so far?

**Comment by gollenia** [comment]
sure, no thing!

**Review by tyxla — APPROVED** [review]
Thanks a bunch, @gollenia 🙌

**Pull request merged**
